import os
import PyInstaller.__main__

SENTINEL_FILE = "_app_mode_flag.py"


def write_sentinel(app_mode: str) -> None:
    """Bake the build mode into a tiny Python module that PyInstaller bundles.

    At runtime, database.py imports this file to decide which DB to use, so
    distinguishing production vs testing no longer depends on the .exe filename
    or any env var being set by the user.
    """
    content = (
        '"""Generated by build.py. DO NOT EDIT — this gets bundled into the exe."""\n'
        f'APP_MODE = {app_mode!r}\n'
    )
    with open(SENTINEL_FILE, "w", encoding="utf-8") as handle:
        handle.write(content)


if __name__ == '__main__':
    print("Packaging Timesheet Tracker using PyInstaller...")

    app_mode = os.environ.get("APP_MODE", "production").strip().lower()
    if app_mode in {"test", "testing"}:
        app_mode = "testing"
        exe_name = "timesheet-test"
    elif app_mode in {"prod", "production"}:
        app_mode = "production"
        exe_name = "timesheet"
    else:
        raise SystemExit(
            f"APP_MODE must be 'production' or 'testing' for builds (got '{app_mode}')"
        )

    write_sentinel(app_mode)
    print(f"Wrote {SENTINEL_FILE} with APP_MODE={app_mode}")

    # We require the Vite output folder to avoid bundling stale legacy builds
    ui_folder_candidates = ["../frontend/dist", "Timesheet/dist"]
    ui_folder = next((p for p in ui_folder_candidates if os.path.exists(p)), None)

    if not ui_folder:
        print("ERROR: React UI dist folder not found! Please run 'npm run build' inside the Timesheet directory first.")
        exit(1)

    PyInstaller.__main__.run([
        'run.py',                         # Main entry point triggering pywebview
        f'--name={exe_name}',             # Name of the exe
        '--windowed',                     # No console window
        '--onefile',                      # Build a single executable file
        '--noconfirm',                    # Overwrite existing dist/build folders
        '--clean',                        # Clean cache

        # Include static files
        f'--add-data={ui_folder};ui',     # Includes UI files into the 'ui' virtual folder

        # Explicit python module imports to ensure FastAPI and uvicorn are bundled correctly
        '--hidden-import=uvicorn.logging',
        '--hidden-import=uvicorn.loops',
        '--hidden-import=uvicorn.loops.auto',
        '--hidden-import=uvicorn.protocols',
        '--hidden-import=uvicorn.protocols.http',
        '--hidden-import=uvicorn.protocols.http.auto',
        '--hidden-import=uvicorn.protocols.websockets',
        '--hidden-import=uvicorn.protocols.websockets.auto',
        '--hidden-import=uvicorn.lifespan',
        '--hidden-import=uvicorn.lifespan.on',

        # Make sure our database backend loads correctly
        '--hidden-import=database',
        '--hidden-import=api',
        '--hidden-import=pdf_export',
        '--hidden-import=sprint_importer',
        '--hidden-import=reportlab',
        # Sentinel that tells database.py which build this is
        '--hidden-import=_app_mode_flag',
    ])

    print("\n--- Packaging Complete ---")
    print(f"App mode baked in: {app_mode}")
    print("Your app should be located in the 'dist' folder!")
